[build]
builder = "dockerfile"

[deploy]
startCommand = "python railway_startup.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Cron job configuration for daily runs at 9 AM Poland time
[cron]
schedule = "0 7 * * *"  # 7 AM UTC = 9 AM Poland time (CEST/CET)
command = "python3 job_monitor_railway.py --test"

# Environment variables (will be set in Railway dashboard)
[env]
PYTHONUNBUFFERED = "1"
TZ = "Europe/Warsaw"
